### ISSUE TITLE
Problem with Pick Slot.Status.Translator Status on translation tool while translating into Czech

### ISSUE THREAD

**Issue by rampa3** [Earthmark/Earthenworks-Translations#9]
I have a problem with string Pick Slot.Status.Translator Status, since you can't fit in both singular and plural version of the string in one line same way in Czech as in English.

Solution ideas? My suggestion would be just having separate singular and plural version of the string, but I am not sure how much mess would that make in the underlying code.

**Comment by rampa3** [comment]
For now, I did this workaround:
![image](https://user-images.githubusercontent.com/68955305/131974368-dab06265-22a8-49ac-9ac4-fa379e2a6a75.png)
It is not pretty, but it works.

**Comment by Earthmark** [comment]
Right now it merges the singular and plural in English. I'll separate them into two strings later today once I get these merged.

**Comment by Earthmark** [comment]
I'll do a string for each line, and each will get a singlar and plural form. It is not a great solution, as it does not handle cases where languages have different tags at different numeric points.

**Comment by rampa3** [comment]
> 
> 
> I'll do a string for each line, and each will get a singlar and plural form. It is not a great solution, as it does not handle cases where languages have different tags at different numeric points.

Wouldn't it be possible to do something like in Neos locales, where the script bases part of the string on number of things by checking the integer and adding fitting string from enum of options then?

**Comment by shadowpanther** [comment]
As a reference: `"World.Indicator.Sessions" : "{n,plural, one {# сессия} few {# сессии} other {# сессий}}",`

**Comment by Earthmark** [comment]
if the system neos uses internally is made available to the general user base then yes it would support that out of the box, but I can't really do that as it is. I'm working inside neos itself, and those primitives are not available outside of the neos core locale file... For now I may leave this as is then, it's odd but solving this is going to be exponentially more difficult from inside of neos...

**Comment by Earthmark** [comment]
The request for early support of the native formatter was rejected: https://github.com/Neos-Metaverse/NeosPublic/issues/2960 so this will not be implemented at this point. I think for now the tool will be restricted to simple formatting.
